### ISSUE TITLE
Provide post-logout advice when appropriate

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/webauthn#15] opened 2016-02-11 00:49 UTC
With some third-party authn systems (including OAuth and Shibboleth), the user is left with third-party cookies that can be used to log back in to our services immediately without re-authenticating to the third-party server. The typical approach to this on other systems is to present the user with a page advising them to shut down their browser. We should extend our providers to return something that the UI can use to provide post-logout advice.

**Comment by karlcz** [comment] 2016-02-20 02:23
I think this might be addressed by #16 and informatics-isi-edu/chaise#208 in combination?

**Comment by hongsudt** [comment] 2016-03-20 03:35
Will close this as it is a duplicate of informatics-isi-edu/chaise#208.

**Closed by hongsudt** 2016-03-20 03:35 UTC
Labels: enhancement
