### ISSUE TITLE
User cache in webauthn doesn't get updated properly

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/webauthn#51] opened 2016-10-04 18:54 UTC
My new profile didn't get reflected in the cache. I needed to delete and then re-login to the system to see the updated profile.

**Comment by ljpearlman** [comment] 2016-10-10 23:40
When I try it, it does update. Please try this:

1. On some host, as the webauthn user, do "psql" and then "select * from "user" where full_name like 'Hongsuda%';

2. Note the values of access_token, access_token_expiration, and the "iat", "exp", and "nbf" values in the userinfo structure.

3. Log out and log in again.

4. Do another query. Compare the values of access_token, access_token_expiration, and the "iat", "exp", and "nbf" values in the userinfo structure with the ones from the previous query.

Did these values change? If not, then there is a bug, and I'll need some help reproducing it, because they change for me. If they do change, and you still think something isn't updating properly, please elaborate. (Note that the guid and username/prefered_username that we get from Globus always correspond to the primary Globus id, regardless of how they authenticate).

**Comment by ljpearlman** [comment] 2016-10-24 20:25
I'm moving this to "review" since it seems to be working for me. If it still seems broken, please say exactly what you're seeing / not seeing that looks wrong (and how to reproduce it).

**Comment by karlcz** [comment] 2016-12-03 00:08
Closing this, and someone can reopen or resubmit if new problems are observed

**Closed by karlcz** 2016-12-03 00:08 UTC
Labels: bug
